/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package iaws.ws.gui;

import iaws.ws.transports.AvailableBikesRequestType;
import iaws.ws.transports.BikeStationType;
import iaws.ws.transports.BikeStationsRequestType;
import iaws.ws.transports.LinesRequestType;
import iaws.ws.transports.RateActionType;
import iaws.ws.transports.RateRequestType;
import iaws.ws.transports.RatedLineType;
import iaws.ws.transports.WSTransport;
import iaws.ws.transports.WSTransportService;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Ilja
 */
public class MainFrame extends javax.swing.JFrame {
    private final WSTransport service;
    private final LinesTableModel linesTableModel;
    private final BikeStationsTableModel bikeStationsTableModel;
    private final StopPointsFrame stopPointsFrame;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        this.setTitle("UPS Transports");
        WSTransportService transportService = new WSTransportService();
        service = new WSTransportService().getWSTransportSoap11();
        List<RatedLineType> lines = service.lines(new LinesRequestType()).getLine();
        linesTableModel = new LinesTableModel(service.lines(new LinesRequestType()).getLine());
        List<BikeStationType> bikeStations = service.bikeStations(new BikeStationsRequestType()).getStation();
        bikeStationsTableModel = new BikeStationsTableModel(bikeStations);
        stopPointsFrame = new StopPointsFrame(service);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLines = new javax.swing.JTable();
        jButtonStops = new javax.swing.JButton();
        jButtonLike = new javax.swing.JButton();
        jButtonDislike = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBikeStations = new javax.swing.JTable();
        jButtonAvailable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableLines.setModel(linesTableModel);
        jScrollPane1.setViewportView(jTableLines);

        jButtonStops.setText("Stops");
        jButtonStops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopsActionPerformed(evt);
            }
        });

        jButtonLike.setText("Like");
        jButtonLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLikeActionPerformed(evt);
            }
        });

        jButtonDislike.setText("Dislike");
        jButtonDislike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDislikeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonStops, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLike, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDislike, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonStops)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLike)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDislike)
                        .addGap(0, 188, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lines", jPanel1);

        jTableBikeStations.setModel(bikeStationsTableModel);
        jScrollPane2.setViewportView(jTableBikeStations);

        jButtonAvailable.setText("Available bikes");
        jButtonAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvailableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAvailable)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAvailable)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Available bikes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLikeActionPerformed
        int selection = jTableLines.getSelectedRow();
        if(selection < 0) {
            return;
        }
        RatedLineType line = linesTableModel.get(selection);
        RateRequestType req = new RateRequestType();
        req.setAction(RateActionType.LIKE);
        req.setLine(line);
        service.rate(req);
        List<RatedLineType> lines = service.lines(new LinesRequestType()).getLine();
        linesTableModel.updateContent(lines);
    }//GEN-LAST:event_jButtonLikeActionPerformed

    private void jButtonDislikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDislikeActionPerformed
        int selection = jTableLines.getSelectedRow();
        if(selection < 0) {
            return;
        }
        RatedLineType line = linesTableModel.get(selection);
        RateRequestType req = new RateRequestType();
        req.setAction(RateActionType.DISLIKE);
        req.setLine(line);
        service.rate(req);
        List<RatedLineType> lines = service.lines(new LinesRequestType()).getLine();
        linesTableModel.updateContent(lines);
    }//GEN-LAST:event_jButtonDislikeActionPerformed

    private void jButtonAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvailableActionPerformed
        int selection = jTableBikeStations.getSelectedRow();
        if(selection < 0) {
            return;
        }
        BikeStationType bikeStation = bikeStationsTableModel.get(selection);
        AvailableBikesRequestType req = new AvailableBikesRequestType();
        req.setStation(bikeStation);
        long availableBikes = service.availableBikes(req).getAvailableBikes();
        JOptionPane.showMessageDialog(this, availableBikes + " available bikes");
    }//GEN-LAST:event_jButtonAvailableActionPerformed

    private void jButtonStopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopsActionPerformed
        int selection = jTableLines.getSelectedRow();
        if(selection < 0) {
            return;
        }
        RatedLineType line = linesTableModel.get(selection);
        stopPointsFrame.update(line);
        stopPointsFrame.setVisible(true);
    }//GEN-LAST:event_jButtonStopsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAvailable;
    private javax.swing.JButton jButtonDislike;
    private javax.swing.JButton jButtonLike;
    private javax.swing.JButton jButtonStops;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableBikeStations;
    private javax.swing.JTable jTableLines;
    // End of variables declaration//GEN-END:variables
}
