
package iaws.ws.transports;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSTransport", targetNamespace = "http://iaws/ws/transports")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSTransport {


    /**
     * 
     * @param bikeStationsRequest
     * @return
     *     returns iaws.ws.transports.BikeStationsResponseType
     */
    @WebMethod(operationName = "BikeStations")
    @WebResult(name = "BikeStationsResponse", targetNamespace = "http://iaws/ws/transports", partName = "BikeStationsResponse")
    public BikeStationsResponseType bikeStations(
        @WebParam(name = "BikeStationsRequest", targetNamespace = "http://iaws/ws/transports", partName = "BikeStationsRequest")
        BikeStationsRequestType bikeStationsRequest);

    /**
     * 
     * @param rateRequest
     */
    @WebMethod(operationName = "Rate")
    @Oneway
    public void rate(
        @WebParam(name = "RateRequest", targetNamespace = "http://iaws/ws/transports", partName = "RateRequest")
        RateRequestType rateRequest);

    /**
     * 
     * @param linesRequest
     * @return
     *     returns iaws.ws.transports.LinesResponseType
     */
    @WebMethod(operationName = "Lines")
    @WebResult(name = "LinesResponse", targetNamespace = "http://iaws/ws/transports", partName = "LinesResponse")
    public LinesResponseType lines(
        @WebParam(name = "LinesRequest", targetNamespace = "http://iaws/ws/transports", partName = "LinesRequest")
        LinesRequestType linesRequest);

    /**
     * 
     * @param stopTimeRequest
     * @return
     *     returns iaws.ws.transports.StopTimeResponseType
     */
    @WebMethod(operationName = "StopTime")
    @WebResult(name = "StopTimeResponse", targetNamespace = "http://iaws/ws/transports", partName = "StopTimeResponse")
    public StopTimeResponseType stopTime(
        @WebParam(name = "StopTimeRequest", targetNamespace = "http://iaws/ws/transports", partName = "StopTimeRequest")
        StopTimeRequestType stopTimeRequest);

    /**
     * 
     * @param stopPointsRequest
     * @return
     *     returns iaws.ws.transports.StopPointsResponseType
     */
    @WebMethod(operationName = "StopPoints")
    @WebResult(name = "StopPointsResponse", targetNamespace = "http://iaws/ws/transports", partName = "StopPointsResponse")
    public StopPointsResponseType stopPoints(
        @WebParam(name = "StopPointsRequest", targetNamespace = "http://iaws/ws/transports", partName = "StopPointsRequest")
        StopPointsRequestType stopPointsRequest);

    /**
     * 
     * @param availableBikesRequest
     * @return
     *     returns iaws.ws.transports.AvailableBikesResponseType
     */
    @WebMethod(operationName = "AvailableBikes")
    @WebResult(name = "AvailableBikesResponse", targetNamespace = "http://iaws/ws/transports", partName = "AvailableBikesResponse")
    public AvailableBikesResponseType availableBikes(
        @WebParam(name = "AvailableBikesRequest", targetNamespace = "http://iaws/ws/transports", partName = "AvailableBikesRequest")
        AvailableBikesRequestType availableBikesRequest);

}
