
package iaws.ws.transports;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSTransportService", targetNamespace = "http://iaws/ws/transports", wsdlLocation = "http://localhost:8080/WSTransport/WSTransport.wsdl")
public class WSTransportService
    extends Service
{

    private final static URL WSTRANSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSTRANSPORTSERVICE_EXCEPTION;
    private final static QName WSTRANSPORTSERVICE_QNAME = new QName("http://iaws/ws/transports", "WSTransportService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WSTransport/WSTransport.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSTRANSPORTSERVICE_WSDL_LOCATION = url;
        WSTRANSPORTSERVICE_EXCEPTION = e;
    }

    public WSTransportService() {
        super(__getWsdlLocation(), WSTRANSPORTSERVICE_QNAME);
    }

    public WSTransportService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSTRANSPORTSERVICE_QNAME, features);
    }

    public WSTransportService(URL wsdlLocation) {
        super(wsdlLocation, WSTRANSPORTSERVICE_QNAME);
    }

    public WSTransportService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSTRANSPORTSERVICE_QNAME, features);
    }

    public WSTransportService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSTransportService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSTransport
     */
    @WebEndpoint(name = "WSTransportSoap11")
    public WSTransport getWSTransportSoap11() {
        return super.getPort(new QName("http://iaws/ws/transports", "WSTransportSoap11"), WSTransport.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSTransport
     */
    @WebEndpoint(name = "WSTransportSoap11")
    public WSTransport getWSTransportSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://iaws/ws/transports", "WSTransportSoap11"), WSTransport.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSTRANSPORTSERVICE_EXCEPTION!= null) {
            throw WSTRANSPORTSERVICE_EXCEPTION;
        }
        return WSTRANSPORTSERVICE_WSDL_LOCATION;
    }

}
